name: ba33_api_client
description: "HTTP API client for ba33 platform"
version: 0.0.1

environment:
  sdk: ^3.11.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.7.0
  ba33_domain:
    path: ../ba33_domain

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
